version: "3.8"

services:
  mysql:
    image: ianlcz/ybc-course-adminbdd-tp4-backup:0.4
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
      - ./backups:/backups
