version:  '3.8'

services:
    mysql:
        image: mysql:8.0.21
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./mysql:/var/lib/mysql
            - ./backups:/backups

    maria:
        image: mariadb:10.5.6
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./maria:/var/lib/mysql
            - ./backups:/backups
